inherit_from:
  - http://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  TargetRubyVersion: 2.4

Lint/DuplicateMethods:
  Enabled: true
  Exclude:
    - lib/krane/psych_k8s_compatibility.rb

Naming/MethodName:
  Exclude:
    - lib/krane/psych_k8s_compatibility.rb