---
name: krane
up:
  - ruby: '3.0.3' # Matches gemspec
  - bundler
  - custom:
      name: Install Kubernetes in Docker (KinD)
      met?: bin/kind version 2>&1 | grep -q v0.11.1
      meet: |
        mkdir -p bin
        curl -sLo bin/kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.11.1/kind-darwin-amd64"
        chmod +x bin/kind
  - custom:
      name: Create KinD Cluster
      met?: bin/kind get clusters | grep -q krane
      meet: bin/kind create cluster --name krane --image "kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047"
      down: |
        ((bin/kind get clusters | grep -q krane) && bin/kind delete cluster --name krane) || true
commands:
  test:
    run: bin/test
  tophat:
    run: PRINT_LOGS=1 bundle exec ruby -I test test/integration/krane_deploy_test.rb -n/${1}/
    desc: Tophat a change by running a test scenario with logging output enabled.
    syntax:
      optional:
        argument: TEST_REGEX
  doc:
    run: bundle exec yard doc
