---
name: krane
up:
  - ruby: 2.5.7 # Matches gemspec
  - bundler
  - homebrew:
      - homebrew/cask/docker:
          or: [homebrew/cask/docker-edge]
  - custom:
      name: Install Kubernetes in Docker (KinD)
      met?: bin/kind version 2>&1 | grep -q 0.8.1
      meet: |
        mkdir -p bin
        curl -sLo bin/kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.8.1/kind-darwin-amd64"
        chmod +x bin/kind
  - custom:
      name: Create Kind cluster
      met?: bin/kind get clusters | grep -q krane
      meet: bin/kind create cluster --name krane --image kindest/node:v1.15.11
      down: ((bin/kind get clusters | grep -q krane) && bin/kind delete cluster --name krane) || true

commands:
  reset-kind: |
    (bin/kind get clusters | grep -q krane) && bin/kind delete cluster --name krane;
    bin/kind create cluster --name krane --image kindest/node:v1.15.11
  test:
    run: bin/test
  tophat:
    run: PRINT_LOGS=1 bundle exec ruby -I test test/integration/krane_deploy_test.rb -n/${1}/
    desc: Tophat a change by running a test scenario with logging output enabled.
    syntax:
      optional:
        argument: TEST_REGEX
  doc:
    run: bundle exec yard doc
