---
name: krane
up:
  - ruby: 2.6.6 # Matches gemspec
  - bundler
  - homebrew:
    - minikube
  - custom:
      name: Minikube Cluster
      met?: test $(minikube status | grep Running | wc -l) -ge 2 && $(minikube status | grep -q 'Configured')
      meet: minikube start --driver=docker --kubernetes-version=v1.18.18
      down: minikube stop
commands:
  reset-minikube: minikube delete && rm -rf ~/.minikube
  test:
    run: bin/test
  tophat:
    run: PRINT_LOGS=1 bundle exec ruby -I test test/integration/krane_deploy_test.rb -n/${1}/
    desc: Tophat a change by running a test scenario with logging output enabled.
    syntax:
      optional:
        argument: TEST_REGEX
  doc:
    run: bundle exec yard doc
