name: Krane CI

on: [push]

jobs:
  ruby-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
        - '3.0' # With k8s 1.21
        - '3.0' # With k8s 1.20
        - '2.7' # With k8s 1.19
        - '2.6.6' # With k8s 1.18
        - '2.6.6' # With k8s 1.17
        include:
        # Match kind images with chosen version https://github.com/kubernetes-sigs/kind/releases
        - ruby: '3.0'
          kind_version: 'v0.11.1'
          kind_image: 'kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6'
        - ruby: '3.0'
          kind_version: 'v0.11.1'
          kind_image: 'kindest/node:v1.20.7@sha256:cbeaf907fc78ac97ce7b625e4bf0de16e3ea725daf6b04f930bd14c67c671ff9'
        - ruby: '2.7'
          kind_version: 'v0.11.1'
          kind_image: 'kindest/node:v1.19.11@sha256:07db187ae84b4b7de440a73886f008cf903fcf5764ba8106a9fd5243d6f32729'
        - ruby: '2.6.6'
          kind_version: 'v0.11.1'
          kind_image: '1.18: kindest/node:v1.18.19@sha256:7af1492e19b3192a79f606e43c35fb741e520d195f96399284515f077b3b622c'
        - ruby: '2.6.6'
          kind_version: 'v0.11.1'
          kind_image: 'kindest/node:v1.17.17@sha256:66f1d0d91a88b8a001811e2f1054af60eef3b669a9a74f9b6db871f2f1eeed00'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "${{ matrix.kind_version }}"
          image: "${{ matrix.kind_image }}"

      - name: Run tests
        run: |
          bin/test
